### ISSUE TITLE
Setup emulator command does not seem to work

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#10]

**Comment by szymonlesisz** [comment]
same with "decision"
steps:
1. run eumulator
2. click wipe 
3. click decision

**Comment by tsusanka** [comment]
Fixed by b41c909d83514feb9c0801ba08ce379566e5ad31.

**Comment by tsusanka** [comment]
I think decisions are still not working properly, but I need to discuss that with @mroz22 first. Moved to #14.
