### ISSUE TITLE
Create regtest section in Dashboard

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-user-env#106]
It could make sense to support regtest in the Dashboard (just some input fields and buttons), so users could easily interact with those (currently two) regtest commands (mining blocks and sending BTC to address)

**Comment by tsusanka** [comment]
If this would be an easy one it would be pretty awesome :).

**Comment by grdddj** [comment]
Done in https://github.com/trezor/trezor-user-env/pull/204
