### ISSUE TITLE
wait for regtest blockbook sync

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-user-env#113]
After you spin up regtest container and connect it with suite blockbook is not fully synchronized yet. 

First run and manually mined block it sends 150 unwanted notifications about mined block (since block 1-150)

we can wait for full synchronization by fetching:
`http://0.0.0.0:19121/api/v2/block-index/150`

if it returns `{"blockHash":"xxxx"}` it means that it's loaded if `{"blockHash":""}` then it's not

**Comment by tsusanka** [comment]
@martinboehm couldn't we somehow dockerize the state where blockbook is synchronized? 🤔

 Btw @szymonlesisz how long does it take cca for the synchronisation to complete?

**Comment by szymonlesisz** [comment]
with thos 150 pre generated blocks almost immediately (few sec)

**Comment by vdovhanych** [comment]
I also had to do this with starting of blocbook service as it would fail if the blocks were still being generated, 5 seconds of sleep was enough time to load it every single time. I think it's like 3-4seconds to sync it.

**Comment by tsusanka** [comment]
As discussed on our meeting we think this should be solved on the other side that is using tenv. Please reopen if you disagree.
