### ISSUE TITLE
Test trezor-user-env

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#122]
We should add tests to this CI that will:
- Launch Bridge
- Launch master emulators
- Launch some specific emulator version

Because otherwise if we mess up something, Suite and other job start to fail and it can get very confusing.

**Comment by grdddj** [comment]
I would try to do it in this sprint, as I am already doing some smaller `tenv` improvements for the `Connect` integration into firmware `CI`. It also means it would be another usage of `tenv`, so possibly another thing to break when `tenv` malfunctions.

Hard to say what is the best way of testing.
- we could just call the functions directly  - `emulator.start()`, `bridge.start()`, but that does not catch any issue in `controller`
- we would probably want to test the whole request/response pipeline, which would mean spinning up the `controller` and creating some mock client sending commands into it and expecting non-error responses
- we do have `bridges` in repository,  so we can spin them immediately, however, we would need to be downloading the `emulators` every time (certainly not all of them, just the `master` ones and some other "random" ones to try)
- test in `docker` container or not? It would probably take a lot of time and resources to always build it - but it could catch `docker` issues
  - we could have this "advanced" testing only in `master`, which is anyway already building `tenv:latest` images per new commit
  - it could be a `postbuild` stage, being dependent on the built image and verifying it runs fine

Just a momentary idea:
- we could have some `health-check` function that would try all possible things (launching bridge, emu, etc.) and all the users of `tenv` would/could call it before using it - and when it would fail, we would not continue with the tests and we would know the current `tenv:latest` is broken

**Comment by grdddj** [comment]
Seems it can be connected with https://github.com/trezor/trezor-user-env/issues/90

**Comment by grdddj** [comment]
This is theoretically also finished - via https://github.com/trezor/trezor-user-env/pull/127

**Overview of the testing**

Quick way how to test a recent production image (but theoretically any instance running locally):
- running `tenv` - `./run.sh`
- spawning tests - `make test_with_running_controller`

There is also `make test`, which spawns `tenv` from the current python codebase, runs the tests, and kills it

**Comment by tsusanka** [comment]
Great 🎉. So the only thing we are missing is to kill Gitlab and move this to GH Actions correct?

**Comment by vdovhanych** [comment]
Yes that should be it

**Comment by tsusanka** [comment]
Moving to https://github.com/trezor/trezor-user-env/issues/163 then 🎉.
