### ISSUE TITLE
Make the tenv:test docker image build manual and take parameters

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-user-env#128]
I think we do not have to build the `tenv:test` image on every commit and every branch, because it is not being used at all (I do not know about any usage currently). It takes about 5 minutes, unnecessarily increases the `CI` time and also consumes resources.

We could make the stage manual, so when somebody wants to build it and use it, they are free to do so. Also, if `Gitlab` allows it, we could create it as a manual job with parameters, so somebody can create for example `tenv:my_feature_for_suite`, which will not be overwritten by somebody else building this "test" image later

**Comment by vdovhanych** [comment]
Good idea, ill assign me to it and try to come up with something that could be more useful than what we have now.

**Comment by vdovhanych** [comment]
This is done by @grdddj , I will improve it a bit by adding the branch name to the tag but that can be done later.
