### ISSUE TITLE
Create screenshotting functionality

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-user-env#137]
As per conversation with @tsusanka and @mroz22, it would be nice to allow `tenv` to make screenshot from the current device screen and send it to the client - most probably through the websocket (maybe as a `base64` encoded data) - or in the worst case, client can take it with `docker cp`

**Comment by grdddj** [comment]
Situation after https://github.com/trezor/trezor-user-env/pull/178 was merged:
- screenshots are supported only for `TT` and `TR`
- support for `T1` is not possible as the screenshots need special `debuglink` commands (through `trezorlib`) during _every_  new connection - which is something we cannot do for example with `Suite`

**Comment by tsusanka** [comment]
Thanks. So I am closing for now!
