### ISSUE TITLE
Interfacing w regtest via suite desktop or web

### ISSUE THREAD

**Issue by humanumbrella** [trezor/trezor-user-env#141]
Hi there --

This repo is great! 

Not sure if this is the right repo to put this in, but since I am utilizing your `Dockerfile` [here](https://github.com/trezor/trezor-user-env/blob/master/docker/bitcoin-regtest/Dockerfile) as the basis for my experiment, I'm going for posting it here ... I am wondering if maybe one of you all can help me out.

I have got a custom regtest node running in another container for another project and I have successfully got `trezor-user-env/docker/bitcoin-regtest` built, running, and connecting to it and it's all seemingly working properly. See below

![Screen Shot 2022-02-11 at 5 15 48 PM](https://user-images.githubusercontent.com/10471648/153690373-0c701815-5fe0-4fe5-920e-d03160ac422a.png)

I can interact with the blockbook and things look great. My problem is that I cannot get this to actually work for my devices when signing transactions, e.g. inside either suite desktop or suite web whether using emulator or actual device. I just get failed to connect, e.g. in Trezor Suite: 

![Screen Shot 2022-02-11 at 5 16 46 PM](https://user-images.githubusercontent.com/10471648/153690425-8a0b1ddd-80a5-44e0-80a9-d7d0743847e7.png)
 
This is despite the fact that I can in fact run through all the tests here: http://0.0.0.0:19121/test-socketio.html and everything works (and i see output in my docker logs)

Here is where I am trying to put it into Trezor Suite

![Screen Shot 2022-02-11 at 5 23 06 PM](https://user-images.githubusercontent.com/10471648/153690663-308d8129-0a0a-48eb-9fe2-d3f643c84fb5.png)

I found this [reddit post]( https://old.reddit.com/r/TREZOR/comments/jshd5j/trouble_connecting_trezor_suite_app_to_private/) which seems to be potentially related.

Any thoughts? Thanks in advance!

**Comment by humanumbrella** [comment]
If I change the settings to
![Screen Shot 2022-02-11 at 5 24 24 PM](https://user-images.githubusercontent.com/10471648/153690699-3366895d-32c4-4810-badb-74176698374a.png)

I get

![Screen Shot 2022-02-11 at 5 24 45 PM](https://user-images.githubusercontent.com/10471648/153690710-9a969eb8-bd46-4f34-ae9e-80bef20c9b9c.png)

This is just a testing playground (it's on regtest!) so I don't really care about https, privacy, or anything. I am just trying to get this working.

I feel like it's so close to working! Let me know what you think

**Comment by humanumbrella** [comment]
errr, so just realized I was putting the custom blockbook on the BTC and not the TBTC ... had to scroll down ... so:
![Screen Shot 2022-02-11 at 5 32 28 PM](https://user-images.githubusercontent.com/10471648/153691018-3756001d-3221-4b31-8762-324bec66f9ae.png)

as compared to
![Screen Shot 2022-02-11 at 5 33 13 PM](https://user-images.githubusercontent.com/10471648/153691050-3c4bc329-5aa7-425f-829f-107f9d1b111e.png)


same problem though:

![Screen Shot 2022-02-11 at 5 32 09 PM](https://user-images.githubusercontent.com/10471648/153690994-26aa92c3-17e2-4848-b08d-2fa6919da506.png)

**Comment by humanumbrella** [comment]
Don't mean to spam here but I am continuing to debug on my end -- I'll document my progress for anyone in the future that may hit this...

Noticed that the `test-socketio` is using ws for the websocket instead of wss

reading more here https://stackoverflow.com/a/46559376/15416503

OK - so either I have use an actual cert on the container [don't like that option right now]- or maybe there's a way to tell suite to drop to ws version bc it's testnet/regtest [probably not in the deployed/live application ?]

**Comment by vdovhanych** [comment]
When interfacing with the bitcoin regtest from trezor suite you should be setting it up as regtest coin in the suite. Accessible with debug mode enabled.
<img width="813" alt="Screenshot 2022-02-12 at 23 14 16" src="https://user-images.githubusercontent.com/45185420/153730205-5f2f1b55-d3e7-4a11-a90a-f30ec29e1b9c.png">

**Comment by humanumbrella** [comment]
How do I launch in debug mode? I haven't been able to find docs on that yet.

**Comment by humanumbrella** [comment]
also found https://docs.trezor.io/trezor-suite/misc/notes.html#debugging-electron-build
but ... am seeing error, what am I doing wrong?
![Screen Shot 2022-02-12 at 11 39 23 PM](https://user-images.githubusercontent.com/10471648/153743775-3b80d254-c697-4080-a0b4-75a87972aff9.png)

**Comment by vdovhanych** [comment]
Go to Settings in Suite
Rapidly click on the "Settings" heading 5 times
After this in coin you should be able to see regtest coin

**Comment by humanumbrella** [comment]
Amazing! Thank you so much. That worked, and it allowed the insecure content which I don't care about right now (because it's regtest and I'm on local testing things out).

One last issue remains -- I am trying to bring this change into a custom app which uses Trezor Connect and I have found 
this comment https://github.com/trezor/connect/issues/45#issuecomment-688754953

and then I found this function https://github.com/trezor/trezor-suite/blob/7296d1b829e5423fffe801097c8b6f53bc70f451/packages/suite/src/actions/wallet/blockchainActions.ts#L135-L145 from [this pr](https://github.com/trezor/trezor-suite/pull/2250/files) to get me going in the right direction.

My app correctly goes to Regtest and starts trying to talk to my blockbook - however, I am getting a mixed content error.

![Screen Shot 2022-02-13 at 9 20 40 PM](https://user-images.githubusercontent.com/10471648/153804729-4dd6553b-5d6f-4889-ba1b-93cda6637756.png)
![Screen Shot 2022-02-13 at 9 20 45 PM](https://user-images.githubusercontent.com/10471648/153804734-9c99d4e6-ce81-4ed7-b6a5-5e0dce90e392.png)

Am I missing one more setting to allow this to work? Any tips? I will keep digging in here to see if I can find something. So close now, hehe. 

Thanks again

**Comment by humanumbrella** [comment]
derp -- this is an easy fix for testing. Will post in case anyone finds this later

```open /Applications/Google\ Chrome.app --args --allow-running-insecure-content```

Closing issue - many thanks @vdovhanych
