### ISSUE TITLE
missing logs from T1 emulator

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-user-env#143]
is it possible to have log from T1 emulator in the same way as we do from T2?
currently only bridge messages are logged to `emulator_bridge.log` while using T1

**Comment by grdddj** [comment]
> is it possible to have log from T1 emulator in the same way as we do from T2? currently only bridge messages are logged to `emulator_bridge.log` while using T1

It is unfortunately not possible to have `T1` logs, as `T1` emulator does not even have logging capabilities.

What would be your use-case for it? We could ask @matejcik how hard it would be to do the logging for `T1`

**Comment by szymonlesisz** [comment]
same usecase as in TT :) debugging. Currently T1 tests in connect are not stable enough and requires multiple retries to pass, this is happening only on CI and we would like to investigate why

**Comment by tsusanka** [comment]
Unfortunately we do not this feature in T1 :(.

**Comment by matejcik** [comment]
just to expand, adding logging to T1 isn't really feasible
