### ISSUE TITLE
remove unused FW binaries

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-user-env#144]
currently we are able to work with T1 >= 1.80 and TT >= 2.1.0. other emulators wont start.
We can save up some space by not downloading them

**Comment by grdddj** [comment]
What are the issues with older emulators? At least locally I was able to spawn even the oldest ones currently (1.6.x and 2.0.x)

**Comment by szymonlesisz** [comment]
i guess it's kinda related to https://github.com/trezor/trezor-user-env/issues/18, you can run it but you are not able to work with it

running tests against lower versions fails on setup with:
```
CONTROLLER: Traceback (most recent call last):
  File "/Workspace/trezor-user-env/src/controller.py", line 63, in get_response
    command_response = self.run_command_and_get_its_response()
  File "/Workspace/trezor-user-env/src/controller.py", line 98, in run_command_and_get_its_response
    return self.run_emulator_command()
  File "/Workspace/trezor-user-env/src/controller.py", line 155, in run_emulator_command
    emulator.setup_device(
  File "/Workspace/trezor-user-env/src/emulator.py", line 239, in setup_device
```

i guess there will be more issues related to that, like DebugLink decisions etc.

**Comment by tsusanka** [comment]
As discussed on our meeting: let's do this server-side and let's not delete them directly, rather move them to some "archive" folder.

**Comment by grdddj** [comment]
The oldest models are currently `T1B1-v1.10.0` and `T2T1-v2.3.0`, so this should be "fixed"
