### ISSUE TITLE
Try to improve caching in Dockerfile

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-user-env#153]
It could be possible to achieve more docker-cache-reuse when building the `image` by moving the `RUN nix-shell --run "./src/binaries/firmware/bin/download.sh"` command closer to the end - so that changes in this layer do not invalidate further layers, which most of the time do not change.

**Comment by tsusanka** [comment]
This is basically a one-liner isn't it? Let's try it? 💪

**Comment by grdddj** [comment]
Looking at it a little more, the cache invalidation in `CI` happens already at `Step 6/17 : COPY ./ ./trezor-user-env`, so any changes after this step do not have any influence on it.

[This](https://gitlab.com/satoshilabs/trezor/trezor-user-env/-/jobs/2249150106), [this](https://gitlab.com/satoshilabs/trezor/trezor-user-env/-/jobs/2253655280) and [this](https://gitlab.com/satoshilabs/trezor/trezor-user-env/-/jobs/2256424368) are `build` jobs from the same commit - `Checking out 8365163e as master...` - but after copying all the `tenv` code (that step 6 above), they produce a different layer hash (all 5 layers before it have `---> Using cache` identifier).

According to some sources - [here](https://stackoverflow.com/a/49957825) and [here](https://forums.docker.com/t/cant-find-why-my-docker-images-digest-are-different-when-building-from-the-exact-same-repo-version/95990/9), the issue is in different timestamps on the files - seems this is caused by us always cloning the repository from scratch on the `CI` server, not reusing existing files. 

I am not sure if this is even worth "fixing" by some script that would always unite the modification time of all files to some constant value. However, I will try for some while, as it has the potential of saving a lot of space and time to pull new images.

**Comment by tsusanka** [comment]
Not worth it as discussed in https://github.com/trezor/trezor-user-env/pull/154. Good idea though!
