### ISSUE TITLE
Include one non-debug emulator for screenshotting purposes

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-user-env#157]
One of the use-cases of `tenv` is screenshotting of the emulator, however, the `debug` red square in the top right corner is annoying.

It would be nice to package one `non-debug` emulator, probably from the latest `master`.

**Comment by tsusanka** [comment]
I do not think that is possible, we need to have debug link to take screenshots and do other instrumentation to work with it. Without debug mode this is not possible. Or am I missing smth?

The best way to get rid of the red square is to have a python script that replaces it with a neighborhood color :). I even wrote that once, but I am afraid it is gone 😢 .

**Comment by vdovhanych** [comment]
Honestly, the easiest way is to just get rid of it in some photo edit tool. Not sure we need to do anything about it.

**Comment by grdddj** [comment]
It turns out that when choosing `Save screenshots` checkbox before starting the emulator, the red square goes away in next screen. (Trezor does some magic at the background, and when it found out the screenshotting mode is on, it does not render the red square even in debug mode)

Actually, Josef Tetek found this when he wanted to do a screenshot without red. I verified it works, we could theoretically have `Screenshot mode` instead of  `Save screenshots`, so users wanting to do it know it can help them

**Comment by grdddj** [comment]
> It would be nice to do this because I think this will be quite common request for mktg/content people.

Or theoretically... why don't we make it a default option to save screenshots and therefore not show the red square? It could save some questions and troubles. Small issue is that the red square appears on the very first screen and disappears only after some interaction with emulator - I will try to find some `screen_refresh` function so that it is red-square-free from the very start.

---

> I have realized i am a bit confused about the screenshoting feature in tenv now. The "Get screenshot" returns a base64 encoded image - I can see that in the log, correct? And that seems to be working regardless the "Save screenshots" checkbox. 

Good point, seems we could improve this a little bit. Actually when you click `Get screenshot`, you will get base64 of the **latest** saved screenshot. So for us, who run `tenv` locally, there will most probably be some "leftover screenshots" from previous sessions. Therefore we get some result even when running emulator without `Save screenshots`. (Solution could be to remove `Get screenshot`, hardly anyone uses it anyway - I think I created it there for testing purposes and then did not delete it.)

---

> So.. what is doing the "Save screenshots" checkbox then? It autosaves screenshots somewhere?

It is telling the starting emulator to save screenshots under `logs/screens`. Our reason to do it is to always have access to the latest screenshot, so we can send the current screen content.

To be clear, `Save screenshots` checkbox does not do any action when you click it while running the emulator - it is only evaluated when you are starting the emulator.

---

As to how to improve the situation/clear the confusion, we could:
- make the `Save screenshots` checkbox a default, and maybe even removing this option from Dashboard
- get rid of the Dashboard's `Get screenshot` - hardly anyone would like to have an encoded image when they could manually create a screenshot

(basically cleaning the `Dashboard` so that users have less confusing things to click on)

---

One half-serious idea, which could be however useful for the people working with Trezor screenshots, would be to offer a "screen dashboard", let's say at `localhost:9003`, where all the screenshots would be visible and ready to be downloaded. Would be fun, but probably not worth the effort - we would need to ask users if they really want to use it and how :)

**Comment by tsusanka** [comment]
> It is telling the starting emulator to save screenshots under logs/screens. Our reason to do it is to always have access to the latest screenshot, so we can send the current screen content.

Could you please check this is true? I have checked the box, launched emulator, but there is nothing in logs/ except debugging.log file.

----

> make the Save screenshots checkbox a default, and maybe even removing this option from Dashboard

Is it a good idea to have it checked by default? It will spam the images folder and take up a lot of space. I think that's not needed if you do not want the images? I would keep it OFF by default.

----

Other than that 👍.

**Comment by grdddj** [comment]
> Could you please check this is true? I have checked the box, launched emulator, but there is nothing in logs/ except debugging.log file.

It works fine for me. However, to save the screenshots locally, `tenv` must be run locally, not from the container - in that case, they will be saved into the `container:/trezor-user-env/src/logs` - I imagine not a lot of people run `tenv` locally without using containers.

> Is it a good idea to have it checked by default? It will spam the images folder and take up a lot of space. I think that's not needed if you do not want the images? I would keep it OFF by default.

Hard to say - making it default could eliminate some questions, but then it would not be apparent if it is a debug emulator or not. On the topic of spamming - it will most certainly not take a lot of space - the images are named like this `img0`, `img1`, `img2`... and with each emulator restart, it start again from `img0`, so they are (in the current situation) overwriting each other, so just the last/longest emulator session is there.

**Conclusion:** (I will make a PR with this)
- Rename `Save screenshots` checkbox to `Screenshot mode (no red square in top right corner)` and leave it `OFF` by default
- Get rid of `Get screenshot` button

**Comment by tsusanka** [comment]
> It works fine for me. However, to save the screenshots locally, tenv must be run locally, not from the container - in that case, they will be saved into the container:/trezor-user-env/src/logs - I imagine not a lot of people run tenv locally without using containers.

Aah so that's it. But we can expose this folder easily via docker-compose nope? That'd be great, could you give it a try? `volumes` is the key word I believe.

**Comment by tsusanka** [comment]
Btw the hovers does not seem to work to me on Chrome 😢 .

**Comment by grdddj** [comment]
> Btw the hovers does not seem to work to me on Chrome cry . But other than that it works great!

I tried the hovers on `Chrome` and `Chromium` and hovers are fine - but I am on `NixOS`

**Comment by tsusanka** [comment]
Ahh, I was to quick, it takes a while 😆 🤦 . All good then! Great, I think this is done!

**Comment by tsusanka** [comment]
Btw it would be great to show this to Ben, Anthonny and maybe others. I think it would really helpful to them. Could you maybe help them also with setting it up?

**Comment by grdddj** [comment]
> Btw it would be great to show this to Ben, Anthonny and maybe others. I think it would be really helpful to them. Could you maybe help them also with setting it up for them? Even if it should be really easy with docker and ./run.sh. Let's teach them that

I agree, let's not keep that secret, it could be helpful for them. I have already shown Josef Tetek, who reached to me, how to run `tenv` - and he actually found out the `screenshot mode` gets rid of the red square :)

I guess we could have some smaller meeting for interested people, who could use the screenshotting feature. Or do them one-by-one?

**Comment by tsusanka** [comment]
Up to you completely :). Maybe first ask who would be interested? Maybe some product channel on Slack? But 100% your call, we can also wait if the words spread :)
