### ISSUE TITLE
Suite does not launch Bridge when tenv is running

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#158]
**Describe the bug**
By default if you run Suite, Bridge is launched just fine but when you are running also tenv it does not launch Bridge for some reason.

**Steps to reproduce:**
1. Launch Suite
2. Go to http://127.0.0.1:21325/status/ - you can see it works just fine
3. Kill Suite
4. Launch tenv via `./run.sh`, wait for it to be run
6. Launch Suite again
7. Suite says Bridge is not running and http://127.0.0.1:21325/status/ does not load up

**Info:**
 - Tenv version: 36d60e3bfe1285a577879053df61801198de35d2
 - Suite version: desktop 22.4.0 (554a4780f0ea58d30b32c7e5b39e3aed65044504)
 - OS: Mac m1

**Note(s):**
Note that if you launch Bridge via tenv's dashboard it works. Also I am not sure if this si Suite's or tenv's bug. cc @vdovhanych @grdddj @matejkriz

**Comment by vdovhanych** [comment]
I assume that's because bridge ports are already in use by the bridge in tenv and suite assume you have installed a standalone bridge maybe?

**Comment by tsusanka** [comment]
> I assume that's because bridge ports are already in use by the bridge in tenv

If I haven't launched Bridge in tenv yet? That does not make sense nope? @grdddj could you maybe check it out?

**Comment by grdddj** [comment]
> > I assume that's because bridge ports are already in use by the bridge in tenv
> 
> If I haven't launched Bridge in tenv yet? That does not make sense nope? @grdddj could you maybe check it out?

I tried to launch the desktop `Suite` on `NixOS`, and the `bridge` was not spawned, regardless of `tenv` running or not.

Logs coming from `Suite` (running `yarn suite:dev:desktop`) show
 ```
2022-04-08T08:16:03.337Z - ERROR(process-trezord): spawn /home/jmusil/trezor-suite/packages/suite-desktop/build/static/bin/bridge/linux-x64/trezord ENOENT
```
in both cases

**Comment by tsusanka** [comment]
Oh yeah NixOS is completely different story, I am mainly interested in macOS. Okay, I guess let's wait till someone from Suite picks it up. Should I make an issue in Suite repo @matejkriz ?

**Comment by matejkriz** [comment]
I don't think it is Suite issue. Try to run `tenv`, do not start the bridge in it, try tu run standalone bridge and you will get the same:

`https: listen tcp 127.0.0.1:21325: bind: address already in use`

I thought that Docker reserve that port (https://github.com/trezor/trezor-user-env/blob/120ac01d96d77b29cebea06ae6a870cbde68b8aa/docker/compose.yml#L13-L17)

**Comment by tsusanka** [comment]
Hmmm 🤔 . You are probably right. I just thought this used to work and this is a regression but maybe it never did.

Hm, this another "do we actually need a standalone bridge" kind of question. Because one has Suite to launch Bridge.. Ok, so let's not worry about this for now? I will close tomorrow unless you disagree :).
