### ISSUE TITLE
arm emulators and bridges with the same version name

### ISSUE THREAD

**Issue by vdovhanych** [trezor/trezor-user-env#159]
Would it be possible to have the emulator and bridge indicate the same version as x86 one? A use case for this is suite integration tests where they call for emulator version `2.4.3` fe. but on arm its `2.4.3-arm` what do you think @grdddj

**Comment by grdddj** [comment]
I guess it could be done just by saving the bridges/emulators _always_ with the same name in `src/binaries/firmware/bin/download.sh`, even if they are `arm` (as we know that the container can contain _either_ `arm` or `nonarm` artifacts, not both, so there will be no name clashes).

As for the implementation of above, there could be some clever bash command that would strip `"-arm"` from the filenames, or we would write some small python script for it.

There would need to be some small changes in `binaries.py`, where we hardcode the bridges for `Dashboard`. 

---

`OR` we would just modify our logic of finding the binaries - when request to spawn `2.4.3` arrives, we could check if it exists, and if not, look for `2.4.3-arm`.

There are multiple ways how to solve this, not sure now what is the best

**Comment by vdovhanych** [comment]
@tsusanka and @grdddj what do you guys think would be the best solution? I don't have any favorites tbh.

**Comment by grdddj** [comment]
I would say the cleanest is this:
- all clients will send just the version, so `2.4.3`, `2-master` etc.
- in `emulator.py` and `bridge.py` we check if we are on `arm` - the already existing `IS_ARM` variable - and if it is, we will just append `-arm` suffix to the version ... `2.4.3` becomes `2.4.3-arm` and the appropriate emulator is searched for in the filesystem

The benefit is that clients do not have to care about anything, the server/websocket/container is responsible for sending them all the valid binaries and then validating they requested a valid one.

**Comment by vdovhanych** [comment]
I like this solution, it's not even that hard to just add it.

**Comment by tsusanka** [comment]
Sounds great 👍.

**Comment by grdddj** [comment]
Alright, let's do it :) @vdovhanych do you want to try implementing it?

**Comment by vdovhanych** [comment]
Not sure i will manage, i have some idea but it didn't work for me :/

**Comment by grdddj** [comment]
Closing as https://github.com/trezor/trezor-user-env/pull/160 is already merged
