### ISSUE TITLE
Get current screen text from T1

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-user-env#169]
@ondracja from `QA` has a requirement to get the current text from `T1` screen.

Use-case:
- during the recovery process, we want to know what word is on screen - the `Cypress` tests need to get this information

Possibilities:
- there could be some way to get that info from `debuglink.state()` object
- we _can_ get a screenshot of the current page, and then somehow extract the text

**Comment by ondracja** [comment]
After a discussion with @mroz22, we belive that we should be able to achieve our use case on our side without any adjustment to the `trezor-user-env` side. I suggest closing this issue for the time being.

**Comment by grdddj** [comment]
Sure, will close it for now. If you would decide to use the `T1` screenshots, please ping us so we can add this to `tenv`, it is not there yet but hopefully could be added quickly.
