### ISSUE TITLE
Make a list of binaries available

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#17]
Make a list in Python of binaries available and serve it via web socket.

**Comment by szymonlesisz** [comment]
send it here https://github.com/trezor/trezor-user-env/blob/master/controller/main.py#L33

**Comment by tsusanka** [comment]
Done in 490df7b76b3eff9de06b3b9396477309cea59517. I don't like that now every time the server is run it needs to do all the listing and sorting. It would be enough to do it at the time of the build/download (like storing an index file and then load that from Python) but it seems like an necessary optimization at the moment.

@szymonlesisz could you rework the javascript/css now to list them?

**Comment by szymonlesisz** [comment]
![Screenshot 2020-10-07 at 18 48 46](https://user-images.githubusercontent.com/3435913/95362026-c9afed80-08cd-11eb-8b0f-3eb06044a871.png)

**Comment by tsusanka** [comment]
Huh, we have released a new FW today and it seems there is an error. Will investigate.

**Comment by tsusanka** [comment]
Fixed. I have run the download script before 4 pm (release time) and you ran it after so it failed just for you :laughing:.

**Comment by tsusanka** [comment]
Thinking about this I put `master` as the first item in the list but maybe that's not a good idea? It might contain some unstable stuff. I'll put it at the end?

**Comment by tsusanka** [comment]
> I'll put it at the end?

Done in 4849d8f2c3735332d9ec8b7ee906e409aa7880fc

**Comment by tsusanka** [comment]
Mostly done by #25.
