### ISSUE TITLE
Add multiple versions of trezorlib

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#18]
Because older firmwares might not work with the newest trezorlib. We can use virtualenv but we could also use Nix for that?

**Comment by szymonlesisz** [comment]
especially `setup` and `decision` might not work

**Comment by tsusanka** [comment]
Let's discuss this with matejcik.

**Comment by tsusanka** [comment]
We will do https://github.com/trezor/trezor-user-env/issues/144 instead, we are not using the old firmwares anyway. Related: https://github.com/trezor/trezor-suite/issues/3728
