### ISSUE TITLE
Change the URL to the latest available model R

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-user-env#189]
It seems the [Gitlab artifact](https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/2498092190/artifacts/raw/core/build/unix/trezor-emu-core) got deleted after some time (1 or 2 months?) and we cannot download the model R emulator anymore.

Should be enough just to change it to some recent `Gitlab` pipeline.

Longer-term the solution is to include `model R` in the firmware `master` build (and then uploading releases to `data.trezor.io`)

**Comment by vdovhanych** [comment]
Yep, that's something we should eventually do. And yes, GitLab artifacts do get deleted after some time.
