### ISSUE TITLE
Check if Bridge is indeed turned off after the container is killed

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#19]

**Comment by tsusanka** [comment]
If I turn on Bridge and then turn off trezor-user-env using `ctrl + c` the Bridge is indeed killed. So I guess that's it.

**Comment by grdddj** [comment]
Yes, the bridge cleanup is baked into `atexit` function. Also, when it runs inside a docker container and the container gets killed, nothing should run inside anymore
