### ISSUE TITLE
emulator setup: passphrase_protection is not working with master FW

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-user-env#202]
there were some changes regarding field name, now it's called apply settings: `use_passphrase`

should we send both to provide fallback for older versions?

**Comment by grdddj** [comment]
If I understand correctly, you are calling `emulator-setup` and instead of `passphrase_protection: bool` you want to specify `use_passphrase: bool`?

**Comment by szymonlesisz** [comment]
i wrote it in a hurry just to have some issue created :)

After investigation it looks like `debuglink.load_device` with `passphrase_protection` true is not working with `2-master` emulator.
protobuf message `LoadDevice` didn't changed and still contains `passphrase_protection` field, so maybe the change was somewhere in `debuglink`?

**Comment by grdddj** [comment]
> i wrote it in a hurry just to have some issue created :)
> 
> After investigation it looks like `debuglink.load_device` with `passphrase_protection` true is not working with `2-master` emulator. protobuf message `LoadDevice` didn't changed and still contains `passphrase_protection` field, so maybe the change was somewhere in `debuglink`?

I am not aware of some recent `debuglink` changes, nor anything changed in `trezoru-user-env` recently.

When it fails with `2-master`, does it work with older emulators? Also, what is the error message you get?

**Comment by grdddj** [comment]
> turns out that ./firmware/bin/download.sh script downloads artifacts only from passed pipelines which happens to be 23 days ago

I had no idea about this.

I am not sure what exactly is broken here, can you please write down some steps how can I replicate it easily?

**Comment by szymonlesisz** [comment]
thb i dont know what happened :)

looks like it works properly with `09ebe293696725813036650b586f7c7d0fce041c` FW revision

sorry for panic, closing
