### ISSUE TITLE
Introduce headless mode

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#22]
For #9 we probably need ability to run the emulators headless. In CI this is probably achieved by `SDL_VIDEODRIVER: dummy` but we might want to introduce it into the HTML controller as well.

**Comment by szymonlesisz** [comment]
if HTML controller will be served from the docker (#21) and if it will show proper status of whats going on (#23) then you don't need to "see" the emulator itself.
It's enough to be able to run it, configure it, click on it (decision)

**Comment by mroz22** [comment]
I suspect that it is not run in headless mode as sometimes it fails with

```
trezor-user-env-unix_1  | POST /listen
trezor-user-env-unix_1  | X Error of failed request:  BadValue (integer parameter out of range for operation)
trezor-user-env-unix_1  |   Major opcode of failed request:  130 (MIT-SHM)
trezor-user-env-unix_1  |   Minor opcode of failed request:  3 (X_ShmPutImage)
trezor-user-env-unix_1  |   Value in failed request:  0x190
trezor-user-env-unix_1  |   Serial number of failed request:  132
trezor-user-env-unix_1  |   Current serial number in output stream:  133
```

**Comment by tsusanka** [comment]
We do not need this. Closing.
