### ISSUE TITLE
Improve errors from the web socket server

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#23]
Sometimes it is not clear what the error is.

**Comment by tsusanka** [comment]
Maybe this is done by #58 as well? :) This is issue is quite general.. Let's close @grdddj?

**Comment by grdddj** [comment]
> Maybe this is done by #58 as well? :) This is issue is quite general.. Let's close @grdddj?

Yes, it is included in this [commit](https://github.com/trezor/trezor-user-env/commit/90646c14224447f24160fa765ab3efa088956bc2#diff-3a64459185e5aa68586d0801d033359b848498ff11c49e1a03e282874fdafd10R152-R155). I think we can close, if there are no other possible improvements
