### ISSUE TITLE
Add developer readme

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-user-env#24]
How to upgrade/modify and build locally the whole thing

**Comment by tsusanka** [comment]
Basic info in https://github.com/trezor/trezor-user-env/commit/9dd4da5e77fb2817e2b3dfe7e601dac88ecfaa72

**Comment by tsusanka** [comment]
I think the [current README](https://github.com/trezor/trezor-user-env#how-to-develop) should cut it! Feel free to open again if needed.
