### ISSUE TITLE
Firmwares - list out of range

### ISSUE THREAD

**Issue by martykan** [trezor/trezor-user-env#244]
Since yesterday's changes our Connect E2E tests have been failing with this type of error: 

https://github.com/trezor/trezor-suite/actions/runs/9454555341

<img width="985" alt="Screenshot 2024-06-10 at 21 51 15" src="https://github.com/trezor/trezor-user-env/assets/8833813/a2cac6d1-8dd0-42ce-9a87-51f3333a81bc">

For now we downgraded to c702cbb2f67ccb39573e529721cb8f1145cdd891 which works.

**Comment by martykan** [comment]
I don't have a very deep understanding of the changes, but I can see the latest version only ships with a limited set of FW binaries.

Before
<img width="730" alt="Screenshot 2024-06-10 at 22 45 49" src="https://github.com/trezor/trezor-user-env/assets/8833813/0ae42bca-cb6e-420f-ad61-e5a1fd05e169">
After
<img width="730" alt="Screenshot 2024-06-10 at 22 46 05" src="https://github.com/trezor/trezor-user-env/assets/8833813/bc196817-124f-445c-87dc-890eb98a7e90">

**Comment by grdddj** [comment]
@szymonlesisz do you have some idea why this happened? Could have been caused by the removal or `--recursive`

**Comment by grdddj** [comment]
I have reverted the changes for the time being - as I had even issues with the download script locally.

All the changes from PR reverted in https://github.com/trezor/trezor-user-env/pull/245

@martykan sorry for the issues, it is my mistake to have merged it without proper testing.
