### ISSUE TITLE
Allow to run external Bridge

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-user-env#252]
When I want to test Desktop Suite (which runs its own bridge) I am getting into a this (which blocks it):
![image](https://github.com/user-attachments/assets/a9805f42-f0f8-4ddf-8c99-0d99c8514aa5)

### Workaround
- Stop Desktop Suite
- Start Trezor Device from `user-env` + load ALL seed if needed
- Start Desktop Suite

**Comment by Hannsek** [comment]
Trezor Suite check during its launch whethere any Bridge is running. If yes, it uses it. If no, it launch its own bridge. 

If you are talking about bridge from `trezor-user-env`, it uses different Bridge that is suitable for communication with the emulator. You can launch this bridge in the debug menu.
@mroz22

**Comment by Hannsek** [comment]
@peter-sanderson Please specify what is the exact issue you want us to fix.

**Comment by peter-sanderson** [comment]
@Hannsek Thanks for explanation, I am still a bit confused by number if bridge variants. But by turning bridge off in Debug and setting up the UdpTransport it works. So closing the issue. 

(My problem was, that that error blocks the UI of user-env and I thought I would "solve it" by stopping the Bridge there.)
