### ISSUE TITLE
Default startup without regtest

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-user-env#273]
So that when user run `./run.sh` it won't run regtest.

**Comment by vdovhanych** [comment]
you can omit the regtest with -r option with `./run.sh -r`

**Comment by grdddj** [comment]
We can easily change it, so that by default, the regtest will not run, and users would need a flag to enable it.

It would break all the current users' flows ... hard to say how many people actually use it, and if it's worth it.

**Comment by Hannsek** [comment]
@vdovhanych yes, I know. However, I suppose that majority of us use it without regtest.

> It would break all the current users' flows

Then it definitely is not worth it.
