### ISSUE TITLE
Parsing of DebugState crashes or does not parse complex types

### ISSUE THREAD

**Issue by M1nd3r** [trezor/trezor-user-env#274]
The parser in `emulator.py` in function `get_debug_state` crashes. This is fixed in https://github.com/trezor/trezor-user-env/pull/271/

However, the fix has a side effect that any fields that are not of type bytes are not present in the result `debug_state_dict`. Szymon added an int parser (for now locally) so the state-of-the-art parser looks like this. It should be replaced by something more robust that is able to parse complex types (mnemonic_type, node, etc.)

```
        for key in dir(debug_state):
            val = getattr(debug_state, key)
            # Not interested in private attributes and non-JSON fields (bytes)
            if key.startswith("__") or key[0].isupper():
                continue
            if isinstance(val, int):
                debug_state_dict[key] = val
            if isinstance(val, bytes):
                try:
                    val = val.decode("utf-8")
                except UnicodeDecodeError:
                    val = val.hex()
                debug_state_dict[key] = val
        return debug_state_dict 
```

**Comment by grdddj** [comment]
I got the error finally when calling the websocket endpoint - it could not convert it to JSON, as there was a method object. I have added a filter that removes methods in https://github.com/trezor/trezor-user-env/pull/271

**Comment by grdddj** [comment]
Resolved in https://github.com/trezor/trezor-user-env/pull/271
