### ISSUE TITLE
Proposal: introduce TREZOR_DEV_WORKSPACE

### ISSUE THREAD

**Issue by darwin** [trezor/trezor-user-env#34]
I noticed that you tend to expect this workflow:

1. developer clones `trezor-user-env` repo
1. developer then runs bunch of scripts, like `init.sh` or `firmware/bin/download.sh`, those script do their job and download/prepare/create some files and folders somewhere under this repo directory tree, e.g. `firmware/bin` or `firmware/repo` or `suite/repo`.

That's ok, but I'd like to propose more flexible approach:

1. developer creates a directory say `~/trezor-dev` and exports global env variable TREZOR_DEV_WORKSPACE pointing to it
1. developer clones `trezor-user-env` repo (typically directly into TREZOR_DEV_WORKSPACE or elsewhere and symlinks it)
1. developer runs bunch of scripts, but they operate on TREZOR_DEV_WORKSPACE, they do not put/generate stuff under trezor-user-env

##### Advantages:

1. TREZOR_DEV_WORKSPACE can be easily deleted and developer can start from scratch
2. developer can operate on multiple TREZOR_DEV_WORKSPACE and be switching between
3. trezor-user-env stays as source code repo and developer does not need to fish for files created as build/download artifacts
4. this is also IntelliJ IDEA friendly setup for newcomers, because (assuming we don't provide .idea configuration) the IDE is gready by default. So when you open idea from trezor-user-env root folder, it picks up `suite/repo` and starts indexing it. This is not something you want to do and you have to go and mark specific directories as excluded. And issues like that. I'm not advocating for treating idea users any special. I'm just advocating for sane directory trees and if we have to fetch something large, to put it on the side at TREZOR_DEV_WORKSPACE level, not inside the source directory tree.
5. one could easily use direnv (.envrc) in TREZOR_DEV_WORKSPACE to control whole environment

**Comment by tsusanka** [comment]
> I noticed that you tend to expect this workflow:

You mean developers of trezor-user-env not users of trezor-user-env (developers of other projects :) ), right? Because developers of other projects that _use_ trezor-user-env do not have to be aware of this repository at all, their "entry point" is the docker image directly that is built daily [on Gitlab](https://gitlab.com/satoshilabs/trezor/trezor-user-env/-/pipelines). They neither clone this repo nor run any shell scripts, everything is ready for them inside the container. Are we on the same page there?

**Comment by tsusanka** [comment]
And as mentioned in the other PR I am not sure the `init.sh` and `[project]/repo` makes sense anymore because everything is fetched either from our sldev.corp website or from Gitlab. I think I should remove it. Sorry about that I understand it was confusing.

**Comment by darwin** [comment]
Is there any doc for someone who want to start hacking on trezor-suite to get everything setup? Ideally from sources?

For my use case. I'm on macOS and I'd like to be able:
1. to run everything directly from mac
2. then optionally in some isolated envrionment (e.g. nix, or docker, or nix-wrapped-in-docker)
3. then optionally I'd like to run test on my beefy machine (WSL2/ubuntu under Windows 10)

I don't want to necessarily rely on some binary blobs downloaded from your CI. I'd like to have option to build everything myself, so when I touch some sources I have a chance to see it.

For me having everything under `~/trezor-dev` sounds like good idea:
- trezor-user-env
- trezor-firmware
- trezor-suite
- ...maybe some other working directories

For example trezor-user-env would be aware of location of trezor-firmware. Or trezor-suite would be aware of location of trezor-user-env.

`~/trezor-dev` would be also good place for me to put some ad-hoc scripts I want but don't want to merge upstream.

**Comment by tsusanka** [comment]
Yes, docs are a bit lacking, we are trying to improve that. You can check out docs.trezor.io but we have way more firmware docs at the moment.

---

I think you can still do all of that. You clone Suite and Firmware and you build as instructed in the repos. You clone trezor-user-env and thanks to your https://github.com/trezor/trezor-user-env/pull/33 you can set the home directory exactly there. I mean it all sounds good I am just wondering if something even needs to be done. Yes we might introduce TREZOR_DEV_WORKSPACE in future but it seems a bit overkill to me at the moment.

**Comment by darwin** [comment]
Ok, feel free to close this issue. I just wanted to share this idea. I can definitely setup my local dev machine to mimic this so it is not a big issue for me. Just maybe wanted this to be an easy default starting situation for new devs.
