### ISSUE TITLE
1.9.3 fails on "allow-unsafe-paths"

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-user-env#40]
Steps to reproduce:
- run T1 (1.9.3  and probably others T1) using UI http://0.0.0.0:21326/
- setup seed
- send `{"type":"emulator-allow-unsafe-paths"}` as json from the UI

it will fail with:
`trezorlib.exceptions.TrezorFailure: DataError: fsm_msg_common.h:366:No setting provided`

https://github.com/trezor/trezor-user-env/blob/master/controller/emulator.py#L236

**Comment by tsusanka** [comment]
T1 does not have this setting if I remember correctly. User env should respond in a better way though, I will fix that. Is this some kind of a blocker for you?

**Comment by tsusanka** [comment]
We can respond from user env with something better to make it clearer. On the other hand T1 responding this way is kind of correct behavior.

**Comment by szymonlesisz** [comment]
it's not possible to run tests in connect with T1 beause of this, i needed to comment this line to make it work

**Comment by szymonlesisz** [comment]
since we already have dedicated message and function only for this (it's not an abstract for apply_settings) i think it should be handled (ignored) for T1 and returned as success.

we are using this only in tests because of prehistorical fixtures with invalid paths

**Comment by tsusanka** [comment]
Ok, will do now.

**Comment by tsusanka** [comment]
Fixed via 13838465149565e464bd8f68db62fecb8e92e476. I'll test it after CI finishes. But do I understand it correctly that the websocket server errored out when this happened? The error should be somehow caught and propagated into the response.

**Comment by tsusanka** [comment]
I'll test it after CI finishes.

> Seems to work..
