### ISSUE TITLE
emulator-start + wipe not working for T1

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-user-env#41]
Steps to reproduce:
- run T1 using UI http://0.0.0.0:21326/ using json command: `{"type":"emulator-start","version":"1.9.3","wipe":true}` 
- click load seed seed button
- run T1 again using json command: `{"type":"emulator-start","version":"1.9.3","wipe":true}` 
- click load seed seed button again

fails with:
` Device is initialized already. Call device.wipe() and try again.`

**Comment by tsusanka** [comment]
Solved by 7ea72f8361b7d23d640a6aedd47f3c2c85b6da4f.
