### ISSUE TITLE
Be more resistent against invalid commands

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#53]
I believe the websocket server fails when you send to it some incorrect command. We should investigate and if it is such case we should send some error message.

**Comment by grdddj** [comment]
Currently, in `controller.py`, it finds out the command is not supported, and sends appropriate error response:
![image](https://user-images.githubusercontent.com/42543243/125191886-f621dd00-e244-11eb-825f-14a96d4f7db1.png)

Also, all the JSON errors and possible missing `type` key (command) are being handled there gracefully
![image](https://user-images.githubusercontent.com/42543243/125191908-24072180-e245-11eb-99b0-ece04da7f032.png)

**Comment by tsusanka** [comment]
https://github.com/trezor/trezor-user-env/blob/incoming/src/controller.py#L139-L143

**Comment by tsusanka** [comment]
https://github.com/trezor/trezor-user-env/blob/bcca9b49affc9939ebe0d5170c061581d1d0a8a6/src/controller.py#L139-L143

**Comment by tsusanka** [comment]
And if we raise some Error it is caught here:

https://github.com/trezor/trezor-user-env/blob/bcca9b49affc9939ebe0d5170c061581d1d0a8a6/src/controller.py#L171-L182

So there is no way currently how to "kill" the controller? Because there were cases when the controller raise an Error and died.

(Btw better than sreenshots is to link the code directly: `https://github.com/trezor/trezor-user-env/blob/bcca9b49affc9939ebe0d5170c061581d1d0a8a6/src/controller.py#L171-L182` . Note that it is not `blob/incoming/src..` but there is a hash instead thanks to which the link stays forever. You get it easily by pressing `y` when on the code github page.)

**Comment by grdddj** [comment]
> So there is no way currently how to "kill" the controller? Because there were cases when the controller raised an Error and died.

I am wondering myself right now, how was it even possible that the CI failed from that bridge RuntimeError (issue #72), if there is this overall try-except in the `controller.py`
- it would feel like the bridge's `stop()` function was called separately and not from the `controller.py`'s websocket while True server loop
- certainly something to look into more closely


> Btw better than sreenshots is to link the code directly

That is a nice feature, thanks for sharing :)

**Comment by tsusanka** [comment]
Let's discuss that in #72. I think this issue can be closed as the main things were solved I believe. We'll open a more particular one if needed.

**Comment by grdddj** [comment]
> Let's discuss that in #72. I think this issue can be closed as the main things were solved I believe. We'll open a more particular one if needed.

Yes, agreed, we can close this one
