### ISSUE TITLE
Pass all fields thru `emulator-apply-settings`

### ISSUE THREAD

**Issue by goodhoko** [trezor/trezor-user-env#54]
The [apply settings](https://github.com/trezor/trezor-user-env/blob/619b5a10f72512f2cb65c34d36ca11352367e66d/controller/main.py#L106-L108) command currently forwards only a single field (`passphrase_always_on_device`) to the emulator. All other fields are silently ignored. This prohibits setting up an emulator with arbitrary features/settings for e2e tests.

_(TODO: @goodhoko link to usecase once a PR is posted.)_

Edit the websocket server so that it passes thru all fields to the emulator when `emulator-apply-settings` is invoked. Optimally make it fail loudly if the client sends a field that is unkown to the running emulator.

cc @tsusanka

**Comment by goodhoko** [comment]
Thanks for addressing this @grdddj! I just noted that I forgot to link the usecase for this. It's the TODO's in this file: https://github.com/trezor/trezor-suite/blob/4a1207a7b9e72c08b224144206e65ba47479fc5b/packages/integration-tests/projects/suite-web/tests/suite/safety-checks-warning.test.ts

But I'd expect more e2e test could leverage this new capability. 😉

**Comment by tsusanka** [comment]
@grdddj if you would like, feel free to contribute what @goodhoko is mentioning. If not we'll leave it for someone in the Suite team :).
