### ISSUE TITLE
No user-facing error when incorrect JSON supplied through HTML dashboard

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-user-env#59]
When user inputs invalid JSON (that cannot be parsed) to be sent to the server, it fails the onSubmit() function and the error message is visible only in the console.

There is no user notification (like *"Please supply valid JSON"*) as an alert or written in red above the input field (or at least in the Log area)

**Comment by tsusanka** [comment]
Closing?

**Comment by grdddj** [comment]
> Closing?

Yes, it was fixed [here](https://github.com/trezor/trezor-user-env/commit/3ef00c2424a9d191dce4b13dc07ce2b56b7287e6#diff-e1485f987b9f8c7e5abe109a80e1bc3e9f45387ac20eabecbb9a339f6fcde1cfR83-R89)
