### ISSUE TITLE
Ping command generates an error in console, as the response is not JSON

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-user-env#60]
Ping request to the server responds just with a string (*pong*) and not with a JSON object, as all other responses, therefore it fails the handleMessage() function (with error visible in the console)

It should be gracefully handled, or the ping response moved into JSON, something like {"success": True, "response": "pong"}

This "response" key could be included in all responses, so that clients are notified of what exactly happened on the background (*"Trezor bridge version 2.0.31 started"*)

We could also have a one-click button in HTML for a quick ping (same as *Exit server* and *Close websocket*)

**Comment by tsusanka** [comment]
I agree! Let's modify it to `{"success": True, "response": "pong"}` and add the one-click button.

**Comment by tsusanka** [comment]
I suggest to close issues that are done in `incoming`. This one is done there as well right?

**Comment by grdddj** [comment]
> I suggest to close issues that are done in `incoming`. This one is done there as well right?

Yes, it was fixed in one of the first [commits](https://github.com/trezor/trezor-user-env/commit/3ef00c2424a9d191dce4b13dc07ce2b56b7287e6#diff-3a64459185e5aa68586d0801d033359b848498ff11c49e1a03e282874fdafd10R66), so it is ready to be closed

**Comment by tsusanka** [comment]
I hope so client did not depend on pure `pong` :). Let's see..

**Comment by grdddj** [comment]
> I hope so client did not depend on pure `pong` :). Let's see..

That would be interesting, hopefully not :)
