### ISSUE TITLE
Bridge binaries in repo are not working in NixOS without modifying them by download.sh

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-user-env#64]
Bridge binaries are already included in repo, in `trezord-go/bin` folder, but when trying to run the application in NixOS, these binaries are not able to start. Error message below:

> /nix/store/2jysm3dfsgby5sw5jgj43qjrb5v79ms9-bash-4.4-p23/bin/sh: /home/user/trezor-user-env/controller/../trezord-go/bin/trezord-go-v2.0.27: No such file or directory

(The file **trezord-go-v2.0.27** exists already from the repository, just seems invisible for NIxOS)

After running the `download.sh` script, all those binaries are updated and they are working fine then. However git sees them as changed files and they could be causing confusion and nuisance when committing etc.

Possible solutions:
- Trying to update the binaries in the repository according to the local changes and seeing if it does not cause any issues in automated CI tests being run in the docker container.
- Putting all those binaries in *.gitignore*, so modifying them locally would not show any git changes

**Comment by tsusanka** [comment]
We definitely do not want to ignore them as then they would be missing in the repo (and therefore on CI). I would try to to run `download.sh` therefore patch them and commit the change (well make a PR) into `incoming`. And then we'll see what happens :).

**Comment by grdddj** [comment]
> We definitely do not want to ignore them as then they would be missing in the repo (and therefore on CI). I would try to to run `download.sh` therefore patch them and commit the change (well make a PR) into `incoming`. And then we'll see what happens :).

Sounds like a plan :)
