### ISSUE TITLE
Bake git revision into the Docker image

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#65]
It would be great to somehow bake git revision (git commit hash) into the docker image. We could print it then in CI and know on which trezor-user-env version we are.

**Comment by grdddj** [comment]
Theoretically we can have a script in Dockerfile that will create something like `version.txt` file inside the image.

This could include the number of commits in the current branch (as a relative identifier of version - the higher amount of commits, the higher the version, plus a branch name) and also detailed information about last N (3?) commits (as running `git log -3`).

It can be then printed as the last pre-CMD step of the Dockerfile, so whenever the container will run in CI tests, this info will be shown.

**Comment by tsusanka** [comment]
Yeah something like that, but I am wondering there might be some best practice here. @vdovhanych maybe you could ask Ondra on some occasion?
