### ISSUE TITLE
Old emulator is bundled inside the docker image

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#91]
For some reason the latest master TT emulator bundled in is from Jul 13th on commit `24bb4016388fca4b998285b95dcd408f4ed0bff6`. This is weird, the revision should be at most one day old as we [fetch](https://github.com/trezor/trezor-user-env/blob/master/firmware/bin/download.sh#L5) the master while building the [docker image](https://github.com/trezor/trezor-user-env/blob/master/docker/Dockerfile#L25) and we do [that](https://github.com/trezor/trezor-user-env/blob/master/.gitlab-ci.yml#L17) [daily](https://gitlab.com/satoshilabs/trezor/trezor-user-env/-/pipeline_schedules).

**How to reproduce**
1. https://github.com/trezor/trezor-user-env/#run-it
2. Launch TT master
3. Call `trezorctl get-featuers | grep revision`.

**Comment by tsusanka** [comment]
Huh I receive https://github.com/trezor/trezor-firmware/commit/10d72b964fd71840595b25ea35a147c73b468fac now correctly :thinking:. I probably did not let the `pull` finish..

**Comment by grdddj** [comment]
I am glad it is resolved even before I took a look on it :)

**Comment by tsusanka** [comment]
You can verify you will get the same result (the same commit I mentioned above).

**Comment by grdddj** [comment]
Yes, I do get that when running master TT from the latest image
![image](https://user-images.githubusercontent.com/42543243/126614166-57ee46a6-b15c-49f7-be6e-bbfabe2b5d22.png)

**Comment by sorooris** [comment]
How did you achieve this? QA's still stuck on [24bb40163](https://github.com/trezor/trezor-firmware/commits/24bb4016388fca4b998285b95dcd408f4ed0bff6) when attempting to run emu via trezor-user-env...

**Comment by grdddj** [comment]
> How did you achieve this? QA's still stuck on 24bb40163 when attempting to run emu via trezor-user-env...

Preparation:
- running these [steps](https://github.com/trezor/trezor-user-env/blob/b7ddfa9616a92fce2d3d38c12fed9d9ed798a61d/README.md#run-it)
  - mainly making sure the `pull`command (step 3) will finish successfully, as it is downloading the latest image of `trezor-user-env` 

On the `index.html` page (at localhost:9002):
- choosing the `2-master` TT emulator from the Trezor T dropdown and pressing `Start` (it will open the emulator)

On your local machine in terminal:
- run `trezorctl get-features | grep revision` (if you do not have `trezorctl`, enter the `nix-shell` in `trezor-user-env` repository)

Feel free to contact me on Slack if still having issues

**Comment by tsusanka** [comment]
We can put `2-master` (and `1-master`) as the first option to increase visibility..

**Comment by grdddj** [comment]
> We can put `2-master` (and `1-master`) as the first option to increase visibility..

Yeah, that would be a very quick change

**Comment by grdddj** [comment]
And should we display them by default, or showing always the latest `released` version - same as now?

![image](https://user-images.githubusercontent.com/42543243/126793418-63d1b0d3-76a7-4e4b-a439-5c58f1502b18.png)

**Comment by tsusanka** [comment]
I think we can make them as default. And let's wait if further complains come :).

**Comment by grdddj** [comment]
> I think we can make them as default. And let's wait if further complains come :).

Agreed, and it is the easier one for implementation (not having to select the second option from the list) :)
